### ISSUE TITLE
fix

### ISSUE THREAD

**Issue by dzhiganov** [sviperm/doctors-list#1]
----html----
2 lang=en?
22 можно заменить на img
28 id Layer_1 дублируется
28 px можно не указывать
36 заменить на button, если возможно
80 div можно заменить на main
90 можно заменить на header
92 лучше заменить div на заголовок
117 судя по названию класса это должен быть список ul > li
250 type можно не указывать

----js----
53 проверку можно сократить, как в строке 69?
105, 106 если переменные принимают только булевы значения, то название начинается с is
140 скобки лишние
150 конструкция не очень. Если хочешь оформить это как отдельную сущность, то вынеси в отдельный класс или объект. 
169 объявление лучше вынести наверх
186 почему let?
202 можно заменить на стрелочную ф-ю
255 см 150 строку
283 можно заменить на forEach?
Дополнение: разбей js на модули, трудновато читать. Погугли IIFE. Константы лучше выносить в начало функции, и именовать капсом CONST_NAME

**Comment by sviperm** [comment]
@delawere 
Все исправил (почти). Наладил загрузку `json` файла с GitHub'a.
На модули разобью потом и соберу с помощью `webpack`

**Comment by sviperm** [comment]
@delawere разбил на модули
